### ISSUE TITLE
Does not work on Safari 14

### ISSUE THREAD

**Issue by kjarex** [intrnl/langit#1]
One can login, but then nothing works.

The console shows the following errors:
![Screenshot 2023-05-25 at 16 09 30](https://github.com/intrnl/langit/assets/2095550/2124f88f-24f7-41df-bf1f-5202f55861e5)

**Comment by intrnl** [comment]
Interesting, I don't have an macOS/iOS device I can use but I can try getting my friend to test, thankfully it's clear that it's coming from the compact notation formatter specifically.

**Comment by intrnl** [comment]
I've changed the Intl locale to en-US, I don't know if that will fix it however, but do try it again

**Comment by kjarex** [comment]
> it does seem like it's only supported on 14.1+
I didn't think it would be relevant to be more specific, but the  version I'e tested it with was 14.1.2

>  I don't really intend on supporting older browsers at the moment
That's absolutely fine. I reported the issue more in a "just so you know" than an "I need a fix" way.

**Comment by intrnl** [comment]
Hmm, then the only other conclusion is that the ICU data is not tied with Safari versions and is instead tied to macOS version

**Comment by TheHCJ** [comment]
It works perfectly on Safari 16 on MacOS

**Comment by intrnl** [comment]
Closing this as I don't feel like supporting Safari in any capacity anymore.
