### ISSUE TITLE
Move to Lexical for post composer

### ISSUE THREAD

**Issue by intrnl** [intrnl/langit#8]
It would be great if we can move away from Tiptap to Lexical for the post composer, this would mean a reduce in bundle size as Lexical has a smaller overall footprint.

This would also mean that Langit might produce a different markup than what Bluesky app does (as it's also using Tiptap for the web composer), but I don't think I'm that concerned.

**Comment by intrnl** [comment]
Lexical was initially chosen for this, but I've had a few struggles getting the mention autocompletion to properly splice and replace the text with a mention.

This could be a bug with the community port of Lexical to Solid, so I think I'd have to do this in React first (with a dummy API) to see if it's the problem of Lexical itself or the port.

**Comment by davedbase** [comment]
I wonder if @mosheduminer is aware that you had this trouble.

**Comment by mosheduminer** [comment]
I was not aware of this, no. I believe that any attempt to use decorator nodes in lexical-solid right now will be buggy, but otherwise things should work correctly. What kind of problems were you facing?

**Comment by intrnl** [comment]
@mosheduminer I'll see if I can make a small reproduction tomorrow or the day after, but the issue I was having is with the text replacement that happens on accepting a suggestion

**Comment by mosheduminer** [comment]
Not exactly. The actual replacement happens through the `onSelectOption` callback there (which calls `$createMentionNode`). I'm not really sure what the `replaceableString` property is for, it doesn't seem to be used by the typeahead plugin currently (though I do see it used in one of the function in the generic menu plugin).

**Comment by intrnl** [comment]
I think my second attempt actually worked this time
https://stackblitz.com/edit/solidjs-templates-fyrvi5

**Comment by mosheduminer** [comment]
Great! I'll check it out tomorrow. I'm the future, if you have an issue with lexical-solid, you can open a discussion in the lexical-solid repo, or ask in the lexical discord.

**Comment by intrnl** [comment]
Page bundle size decreased by ~36 kB gzipped
